name: production-calculator-staging
services:
    backend:
        container_name: backend-staging
        ports:
            - 5142:5000
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging

    postgres:
        container_name: postgres-staging
        ports:
            - 5152:5432

    flyway:
        container_name: flyway-staging

    prometheus:
        container_name: prometheus-staging
        ports:
            - "5162:9090"
    loki:
        container_name: loki-staging
        ports:
            - "5172:3100"

    promtail:
        container_name: promtail-staging

    grafana:
        container_name: grafana-staging
        ports:
            - "5182:3000"
