name: production-calculator-prod

networks:
    shared-network:
        name: calculator-prod-network

services:
    backend:
        container_name: backend-prod
        ports:
            - 5143:5000
        environment:
            - ASPNETCORE_ENVIRONMENT=Production

    prometheus:
        container_name: prometheus-prod

    loki:
        container_name: loki-prod

    promtail:
        container_name: promtail-prod
        environment:
            - PROJECT_NAME=${COMPOSE_PROJECT_NAME:-production-calculator-prod}

    grafana:
        container_name: grafana-prod
        ports:
            - "5183:3000"
