name: production-calculator-staging

networks:
    shared-network:
        name: calculator-staging-network

services:
    backend:
        container_name: backend-staging
        ports:
            - 5142:5000
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - PasswordReset__FrontendBaseUrl=https://staging.production-calculator.com
            - Jwt__Key=${JWT_KEY:?JWT_KEY must be set}

    prometheus:
        container_name: prometheus-staging

    loki:
        container_name: loki-staging

    promtail:
        container_name: promtail-staging
        environment:
            - PROJECT_NAME=${COMPOSE_PROJECT_NAME:-production-calculator-staging}

    grafana:
        container_name: grafana-staging
        ports:
            - "5182:3000"
